name: Publish Node-14
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'node/node-14/**'
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: set up Docker builder
        uses: docker/setup-buildx-action@v1
      - name: log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
      - name: push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: 'node/node-14/node-14.dockerfile'
          tags: ghcr.io/cahllagerfeld/node-14:latest

  